export const PREDEFINED_ZONES = {
  Dhaka: [
    "Uttara",
    "Mirpur",
    "Dhanmondi",
    "Gulshan",
    "Banani",
    "Mohammadpur",
    "Badda",
    "Khilgaon",
    "Bashundhara R/A",
    "Baridhara",
    "Tejgaon",
    "Mogbazar",
    "Motijheel",
    "Wari",
    "Jatrabari"
  ],
  Sylhet: [
    "Amberkhana",
    "Zindabazar",
    "Shibgonj",
    "Uposhahar",
    "Bagbari",
    "Lamabazar",
    "Subhanighat",
    "Kadamtali",
    "Kumarpara",
    "Mendibag",
    "Pathantula",
    "Shahjalal Uposhahar",
    "Akhalia",
    "Eidgah",
    "Majortilla"
  ],
  Khulna: [
    "Sonadanga",
    "Boyra",
    "Khalishpur",
    "Daulatpur",
    "Shibbari",
    "Rupsha",
    "Gollamari",
    "Nirala",
    "Mujgunni",
    "Tutpara",
    "Khulna Sadar",
    "Sonadanga R/A",
    "Boyra R/A",
    "Shiromoni",
    "Phultala"
  ],
  Chattogram: [
    "Halishahar",
    "GEC Circle",
    "Agrabad",
    "Khulshi",
    "Nasirabad",
    "Lalkhan Bazar",
    "Chawkbazar",
    "Patenga",
    "Chandgaon",
    "Panchlaish",
    "Muradpur",
    "Double Mooring",
    "Kotwali",
    "Bakalia",
    "Bahaddarhat"
  ]
};
