/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: "1rem",
        sm: "1.5rem",
        lg: "2rem",
        xl: "2rem",
      },
    },
    extend: {
      colors: {
        // Google Stitch Theme Tokens
        "surface-container-highest": "#dae2fd",
        "on-surface-variant": "#464554",
        "primary-fixed": "#e3dfff",
        "on-tertiary-container": "#bebfff",
        "on-primary-fixed-variant": "#372abf",
        "outline-variant": "#c7c4d7",
        "on-primary-fixed": "#100069",
        "secondary": "#006c49",
        "background": "#faf8ff",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#c3c0ff",
        "surface-variant": "#dae2fd",
        "on-surface": "#131b2e",
        "error": "#ba1a1a",
        "surface": "#faf8ff",
        "primary-container": "#4338ca",
        "secondary-container": "#6cf8bb",
        "on-secondary-fixed-variant": "#005236",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "on-primary-container": "#c1beff",
        "surface-tint": "#5148d7",
        "on-primary": "#ffffff",
        "secondary-fixed": "#6ffbbe",
        "surface-container": "#eaedff",
        "on-background": "#131b2e",
        "on-secondary-fixed": "#002113",
        "tertiary": "#1f1ab3",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#c0c1ff",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#c3c0ff",
        "surface-dim": "#d2d9f4",
        "inverse-on-surface": "#eef0ff",
        "secondary-fixed-dim": "#4edea3",
        "tertiary-fixed": "#e1e0ff",
        "primary": "#2a14b4",
        "on-error": "#ffffff",
        "on-secondary-container": "#00714d",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "inverse-surface": "#283044",
        "on-tertiary-fixed": "#07006c",
        "error-container": "#ffdad6",
        "tertiary-container": "#3b3bc9",
        "outline": "#777586",
        "surface-bright": "#faf8ff",
        "surface-container-high": "#e2e7ff",

        brand: {
          50: '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
        },

        // Existing palette compatibility
        tv: {
          primary: "var(--color-primary)",
          "primary-hover": "var(--color-primary-hover)",
          secondary: "var(--color-secondary)",
          accent: "var(--color-accent)",
          bg: "var(--color-bg)",
          surface: "var(--color-surface)",
          text: "var(--color-text)",
          "text-muted": "var(--color-text-muted)",
          success: "var(--color-success)",
          warning: "var(--color-warning)",
          danger: "var(--color-danger)",
          border: "var(--color-border)",
        },
        accent: {
          DEFAULT: "#F5A524",
          50: "#FFFBEB",
          500: "#F5A524",
          600: "#D97706",
        },
        canvas: "#F7F8FB",
        ink: {
          DEFAULT: "#1A1D29",
          muted: "#5B5F73",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        sm: "8px",
        md: "12px",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      boxShadow: {
        sm: "0 1px 2px rgba(16, 17, 26, 0.06)",
        md: "0 4px 16px rgba(16, 17, 26, 0.08)",
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', '"Inter"', '"Hind Siliguri"', "sans-serif"],
        "display-hero": ['"Plus Jakarta Sans"', "sans-serif"],
        "display-hero-mobile": ['"Plus Jakarta Sans"', "sans-serif"],
        "headline-lg": ['"Plus Jakarta Sans"', "sans-serif"],
        "headline-lg-mobile": ['"Plus Jakarta Sans"', "sans-serif"],
        "headline-md": ['"Plus Jakarta Sans"', "sans-serif"],
        "headline-sm": ['"Plus Jakarta Sans"', "sans-serif"],
        "body-lg": ['"Plus Jakarta Sans"', "sans-serif"],
        "body-md": ['"Plus Jakarta Sans"', "sans-serif"],
        "body-sm": ['"Plus Jakarta Sans"', "sans-serif"],
        "label-lg": ['"Plus Jakarta Sans"', "sans-serif"],
        "label-md": ['"Plus Jakarta Sans"', "sans-serif"],
        "label-sm": ['"Plus Jakarta Sans"', "sans-serif"],
      },
      fontSize: {
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-hero-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-hero": ["48px", { lineHeight: "56px", letterSpacing: "-0.03em", fontWeight: "800" }],
      },
    },
  },
  plugins: [],
};
